server:
  port: 7001

spring:
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: dev1
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
    #不注册自己
    register-with-eureka: false
  #禁用自我保护模式
  server:
    enable-self-preservation: false


