server:
  port: 8082
  servlet:
    context-path: /schedule

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/h_sword?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: h-sword
#  redis:
#    host: localhost
#    port: 6379
#    timeout: 1000


#swagger:
#  enable: true
#knife4j:
#  production: true



## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.springboot.schedule.model  # 注意：对应实体类的路径

#pagehelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

